### ISSUE TITLE
Multiple workers?

### ISSUE THREAD

**Issue by rtu-dataframe** [ClimenteA/kerground#1]
Hi, great job mate!

In my project, i have different queues that needs to be executed using different workers, to do so, in python-rq the only needed thing that i have to do is to start the rqworker with the different names of the worker queue, for example:

- rqworker my_worker_1
- rqworker my_worker_2
- rqworker my_worker_3 

How i can do this using your package? also, i've seen that you use Threads and ThreadPoolExecutor...have you tested the thread safety? 
In the past i've done some tests using threads and i've noticed some memory-related problems.

**Comment by ClimenteA** [comment]
Hi, thank you!

Just merged your pull request, I will update on pypi soon.

I haven't test it for threading issues, but as long function workers to "independent"  tasks there should be no problem.

Thank you for your contribution!
