### ISSUE TITLE
Sqlite concurrency problems

### ISSUE THREAD

**Issue by rtu-dataframe** [ClimenteA/kerground#3]
I know that Sqlite is not the "best" in managing concurrency, but i've noticed that the sqlite database has some problems when i use this workflow:

- Start a python script and istantiate the kerground queue
- Start a kerground worker
- Do a for loop that adds 10000 jobs to the queue

The worker will go in exception, reporting that the Sqlite db file is locked.

Maybe a change to kerground core is needed? i've modified the kerground core using the `journal_mode = WAL`, but this not helps anyway.

Maybe we have to change the data persistency and use something alternative (maybe only files?)

**Comment by ClimenteA** [comment]
Indeed SQLite writes are blocked if they come at the same time.

File based may solve this issue or another database? RethinkDB?

Or another embeddable db:
https://github.com/gostor/awesome-go-storage

If you find a way to solve this issue using a file based solution go for it.

**Comment by ClimenteA** [comment]
Got some time to work on it. Ditched sqlite for json files for storing queue. I think it's much more better now.
